import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { createBroadcastPersonalizationClient } from "../packages/cli/dist/operator-broadcast-personalization-client.js";
import { createCoreOperatorClient } from "../packages/cli/dist/operator-client.js";
import { createBroadcastRenderToolHandler, createBroadcastPersonalizationSchemaToolHandler } from
  "../packages/cli/dist/mcp-broadcast-render-test-tools.js";
import { renderBroadcastDraftInputSchema, renderBroadcastDraftOutputSchema } from "../packages/cli/dist/mcp-broadcast-render-types.js";
import { readBroadcastPersonalizationSchemaInputSchema } from "../packages/cli/dist/mcp-broadcast-personalization-types.js";
import { parseOperatorArguments } from "../packages/cli/dist/operator-arguments.js";
import { runOperatorCommand } from "../packages/cli/dist/operator-run.js";
import { hostedConfig } from "./fixtures/cli-production-broadcast-responses.mjs";
const configUrl = "http://127.0.0.1:8580/.well-known/fonte-cli.json";

// Generated by Core's broadcastPersonalizationSchema; joined DB proof compares real responses.
const contract = JSON.parse(await readFile(new URL("./fixtures/broadcast-personalization-schema.json", import.meta.url), "utf8"));
const workspace = "synthetic-personalization";
const draftId = "00000000-0000-4000-8000-000000000858";
const schemaVersion = contract.schema.schemaVersion;
const input = { workspace, draftId, revision: 4, schemaVersion, sample: { kind: "synthetic_missing" } };

test("SDK and existing MCP render pass through exact Core schema, warnings, references and spans", async () => {
  const calls = [];
  const schema = { ...contract, schema: { ...contract.schema,
    customFields: [{ key: "tier", path: "custom.tier", label: "Tier", type: "string", nullable: true, state: "active", available: true },
      { key: "retired", path: "custom.retired", label: "Retired", type: "number", nullable: true, state: "deleted", available: false }] } };
  const core = validMissing();
  // No adapter repairs fallback, reference, source span or Core diagnostic data.
  const client = createBroadcastPersonalizationClient(async (path, options) => {
    calls.push({ path, options });
    return options ? core : schema;
  });
  const discovered = await createBroadcastPersonalizationSchemaToolHandler(async () => client)({ workspace });
  assert.deepEqual(discovered.schema, schema);
  const rendered = await createBroadcastRenderToolHandler(async () => client)({
    workspace, draft_id: draftId, revision: 4, personalization_schema_version: schemaVersion, sample: input.sample,
  });
  assert.deepEqual(rendered.render, core);
  assert.equal(renderBroadcastDraftOutputSchema.safeParse(rendered).success, true);
  assert.deepEqual(calls, [{ path: `/v1/workspaces/${workspace}/marketing-broadcasts/personalization-schema?environment=production`, options: undefined },
    { path: `/v1/workspaces/${workspace}/marketing-broadcasts/${draftId}/send-approvals?environment=production`,
      options: { lostResponseEffect: "none", body: { operation: "render_personalization_preview",
        expectedVersion: 4, schemaVersion, sample: input.sample } } }]);
});

test("unknown and malformed diagnostics survive SDK/MCP unchanged and do not throw away blocking spans", async () => {
  for (const code of ["personalization_unknown_field", "personalization_malformed_expression", "personalization_unknown_custom_field"]) {
    const response = invalid(code);
    const client = createBroadcastPersonalizationClient(async () => response);
    const result = await createBroadcastRenderToolHandler(async () => client)({ workspace, draft_id: draftId,
      revision: 4, personalization_schema_version: schemaVersion, sample: input.sample });
    assert.deepEqual(result.render.diagnostics, response.diagnostics);
    assert.equal(result.render.status, "invalid");
    assert.equal(result.core_effect, "none");
  }
});

test("SDK and MCP reject caller definitions or recipient values before any request", async () => {
  let calls = 0;
  const client = createBroadcastPersonalizationClient(async () => { calls++; return contract; });
  await assert.rejects(client.previewBroadcastPersonalization({ ...input, customFields: [{ key: "claimed", type: "string" }] }));
  await assert.rejects(client.previewBroadcastPersonalization({ ...input, sample: { kind: "synthetic_missing", values: { first_name: "claimed" } } }));
  assert.equal(calls, 0);
  assert.equal(readBroadcastPersonalizationSchemaInputSchema.safeParse({ workspace, customFields: [] }).success, false);
  const mcp = { workspace, draft_id: draftId, revision: 4, personalization_schema_version: schemaVersion, sample: input.sample };
  assert.equal(renderBroadcastDraftInputSchema.safeParse({ ...mcp, customFields: [] }).success, false);
  assert.equal(renderBroadcastDraftInputSchema.safeParse({ ...mcp, sample: undefined }).success, false);
  assert.equal(renderBroadcastDraftInputSchema.safeParse({ ...mcp, personalization_schema_version: undefined }).success, false);
});

test("mismatched Core schema and saved revision fail closed without an effect", async () => {
  for (const change of [{ draftVersion: 9 }, { environment: "sandbox" },
    { schema: { ...contract.schema, schemaVersion: "different" } },
    { manifest: { schemaVersion: "different", fields: [], references: [] } }]) {
    const client = createBroadcastPersonalizationClient(async () => ({ ...invalid("personalization_unknown_field"), ...change }));
    await assert.rejects(client.previewBroadcastPersonalization(input), error =>
      error.reason === "core_operator_receipt_invalid" && error.coreEffect === "none");
  }
});

test("CLI commands use the shared authenticated operator requester and retain the machine contract", async () => {
  const parsed = parseOperatorArguments(["broadcast", "personalization", "schema", "--workspace", workspace,
    "--environment", "production", "--json"]);
  assert.equal(parsed.command.kind, "broadcast_personalization_schema");
  const urls = [];
  const receipt = await runOperatorCommand(parsed.command, {
    configUrl, authorize: async () => "synthetic-bearer", sleep: async () => assert.fail("no polling"),
    readProviderEvidenceCandidateFile: async () => assert.fail("no provider evidence"),
    readProviderPlacementApplicationFile: async () => assert.fail("no provider placement"),
    fetch: async (url, init) => {
      urls.push({ url: String(url), method: init?.method });
      return new Response(JSON.stringify(String(url) === configUrl ? hostedConfig("https://core.fixture.invalid") : contract));
    },
  }, () => assert.fail("no mutation identity"));
  assert.equal(receipt.outcome, "completed");
  assert.equal(receipt.core_effect, "none");
  assert.deepEqual(receipt.result, contract);
  assert.equal(urls.length, 2);
  const preview = parseOperatorArguments(["broadcast", "personalization", "preview", "--workspace", workspace,
    "--environment", "production", "--draft-id", draftId, "--revision", "4", "--schema-version", schemaVersion,
    "--sample", "selected", "--contact-id", "selected-fixture", "--recipient-email", "independent@fixture.invalid"]);
  assert.deepEqual(preview.command.sample, { kind: "selected_contact", contactId: "selected-fixture", recipientEmail: "independent@fixture.invalid" });
  const sdk = createCoreOperatorClient({ coreApiBaseUrl: "https://core.fixture.invalid", bearer: "synthetic", fetch: async () => new Response(JSON.stringify(contract)) });
  assert.deepEqual(await sdk.readBroadcastPersonalizationSchema({ workspace }), contract);
});

function invalid(code) {
  return { kind: "broadcast_personalization_preview", tenantId: contract.tenantId, environment: "production",
    broadcastDraftId: draftId, draftVersion: 4, schema: contract.schema,
    manifest: { schemaVersion, fields: [], references: [] }, sample: input.sample,
    diagnostics: [{ code, severity: "error", location: "html", span: { start: 3, end: 19 },
      token: "{{ frist_name }}", path: "frist_name", message: "Core correction", correction: "{{ first_name }}" }],
    effect: "none", status: "invalid", preview: null };
}

function validMissing() {
  const digest = `sha256:${"a".repeat(64)}`;
  const warnings = [{ code: "personalization_missing_fallback", severity: "warning", location: "html",
    span: { start: 3, end: 19 }, token: "{{ first_name }}", path: "first_name", message: "Add an authored fallback if desired" }];
  return { ...invalid("unused"), status: "valid", diagnostics: warnings,
    manifest: { schemaVersion, fields: [{ path: "first_name", type: "string", nullable: true }],
      references: [{ path: "first_name", token: "{{ first_name }}", fallback: null, location: "html", span: warnings[0].span }] },
    preview: { status: "preview", broadcastDraftId: draftId, environment: "production", renderContentDigest: digest,
      html: "<p>{{ first_name }}</p>", text: "{{ first_name }}", renderProof: {
        templateRevision: contract.schema.templateRevision, rendererVersion: contract.schema.rendererVersion,
        recipientSlotSchemaVersion: schemaVersion, finalizerVersion: contract.schema.finalizerVersion,
        broadcastVersion: 4, renderHash: digest }, sampleRender: { recipientEmail: "preview-recipient@example.invalid",
        subject: "Hello", preheader: null, html: "<p></p>", text: "", finalizerVersion: contract.schema.finalizerVersion,
        diagnostics: warnings, valueSource: { kind: "synthetic_missing" } } } };
}
